# Generated by Django 2.2.4 on 2019-08-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aritcle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('publish_data', models.DateTimeField()),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
