# Generated by Django 2.2.4 on 2019-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190811_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aritcle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
